# 1. server config
server:
  port: 8080

# 2. Spring config
spring:
  # 2-1. Servlet ??
  servlet:
    multipart:                    # Multi-part ?? ??? ?? ??
      max-file-size: 10MB         # ?? ??? ?? ??? 10MB? ??
      max-request-size: 10MB      # ?? ? ?? ??? 10MB? ??
  # 2-2. Spring MVC ??
  mvc:
    static-path-pattern: /static/**   # ?? ??? URL ?? ??? /static/**? ?? (????? ?? ???)
